name: Exercice Node.js

# 1. Configuration pour être lancé manuellement
on:
  workflow_dispatch:

jobs:
  setup-node-job:
    runs-on: ubuntu-latest
    
    steps:
      # 2. Installation de Node.js version 18 avec l'action spécifiée
      - name: Installer Node.js 18
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '18'

      # 3. Affichage de la version installée dans la sortie
      - name: Vérifier la version
        run: node -v
